volumes:
  pg_data:

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    container_name: postgres_conteiner
    image: postgres:17-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network


networks:
  app-network: