volumes:
  pg_data:

services:

  db:
    container_name: postgres_conteiner
    image: postgres:17-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    container_name: redis_conteiner
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
  
  backend:
    container_name: backend
    build: .
    ports:
      - 8001:8000
      - 5556:5555
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - app-network

networks:
  app-network: