volumes:
  pg_data:

services:

  redis:
    container_name: redis_conteiner
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
  db:
    container_name: postgres_conteiner
    image: postgres:17-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  backend:
    build: ./backend/
    env_file: .env
    networks:
      - app-network
    depends_on:
      - db

  celery:
    build: ./celery_app/
    env_file: .env
    networks:
      - app-network
    depends_on:
      - backend


networks:
  app-network: